- Câu 1: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor từ danh sách 1 chiều?

In [3]:
import numpy as np
import tensorflow as tf 
import torch

In [4]:
list_1D = [1,2,3,4,5,6,7,8,9]

In [5]:
arr_1D = np.array(list_1D)
print("Mảng 1 chiều Numpy:\n", arr_1D, type(arr_1D))

Mảng 1 chiều Numpy:
 [1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [6]:
arr_1D = torch.tensor(list_1D)
print("Mảng 1 chiều Pytorch:\n", arr_1D, type(arr_1D))

Mảng 1 chiều Pytorch:
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) <class 'torch.Tensor'>


In [9]:
arr_1D = tf.convert_to_tensor(list_1D)
print("Mảng 1 chiều Tensorflow:\n", arr_1D, type(arr_1D))

Mảng 1 chiều Tensorflow:
 tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>


- Câu 2: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor từ danh sách 2 chiều. Sau |đó thực hiện kiểm tra thuộc tính shape, dtype, type, device từ các array, tensor vừa tạo ?

In [10]:
# Tạo một danh sách 2 chiều
list_2D = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# Tạo một tensor 2 chiều
tensor_2D_pt = torch.tensor(list_2D)

# Kiểm tra hình dạng, kiểu dữ liệu, loại, thiết bị lưu trữ của tensor
print("Hình dạng của tensor: ", tensor_2D_pt.shape)
print("Kiểu dữ liệu của tensor: ", tensor_2D_pt.dtype)
print("Loại của tensor: ", type(tensor_2D_pt))
print("Thiết bị lưu trữ của tensor: ", tensor_2D_pt.device)
print("Tensor:\n", tensor_2D_pt)

Hình dạng của tensor:  torch.Size([3, 3])
Kiểu dữ liệu của tensor:  torch.int64
Loại của tensor:  <class 'torch.Tensor'>
Thiết bị lưu trữ của tensor:  cpu
Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [11]:
# Tạo một danh sách 2 chiều
list_2D = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# Tạo một tensor 2 chiều từ danh sách
tensor_2D_tf = tf.convert_to_tensor(list_2D)

# Kiểm tra hình dạng, kiểu dữ liệu, loại, thiết bị mà tensor được lưu trữ
print("Hình dạng của tensor: ", tensor_2D_tf.shape)
print("Kiểu dữ liệu của tensor: ", tensor_2D_tf.dtype)
print("Loại của tensor: ", type(tensor_2D_tf))
print("Thiết bị mà tensor được lưu trữ: ", tensor_2D_tf.device)
print(tensor_2D_tf)

Hình dạng của tensor:  (3, 3)
Kiểu dữ liệu của tensor:  <dtype: 'int32'>
Loại của tensor:  <class 'tensorflow.python.framework.ops.EagerTensor'>
Thiết bị mà tensor được lưu trữ:  /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
