In [2]:
import numpy as np
np.random.seed(2024)
import torch
torch.manual_seed(2024)
import tensorflow as tf
tf.random.set_seed(2024)

- Câu 1: Viết chương trình tạo hai Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số nguyên ngẫu nhiên trong khoảng [-10, 10) với kích thước (3, 4). Sau đó chuyển vị array, tensor thứ 2 và thực hiện phép nhân matrix multiplication. Lưu ý: sử dụng seed=2024

In [4]:
arr_1 = np.random.randint(-10, 10, (3, 4))
arr_2 = np.random.randint(-10, 10, (3, 4))

arr_2_transposed = np.transpose(arr_2)

result_matmul = np.matmul(arr_1, arr_2_transposed)

print("array 1:\n", arr_1)
print("array 2:\n", arr_2)
print("array 2 sau khi chuyển vị:\n", arr_2_transposed)
print("Kết quả phép nhân arr_1 với  arr_2:\n", result_matmul )

array 1:
 [[  9  -6  -2   8]
 [ -9   0  -3   6]
 [ -2   3 -10 -10]]
array 2:
 [[ 1  3 -4  1]
 [ 6  5 -4 -3]
 [-2  3  6 -2]]
array 2 sau khi chuyển vị:
 [[ 1  6 -2]
 [ 3  5  3]
 [-4 -4  6]
 [ 1 -3 -2]]
Kết quả phép nhân arr_1 với  arr_2:
 [[  7   8 -64]
 [  9 -60 -12]
 [ 37  73 -27]]


In [8]:
tensor_1 = torch.randint(-10, 10, (3, 4))
tensor_2 = torch.randint(-10, 10, (3, 4))

tensor_2_transposed = tensor_2.T

result_matmul = torch.matmul(tensor_1, tensor_2_transposed)

print("array 1:\n", tensor_1)
print("array 2:\n", tensor_2)
print("array 2 sau khi chuyển vị:\n", tensor_2_transposed)
print("Kết quả phép nhân arr_1 với  arr_2:\n", result_matmul )

array 1:
 tensor([[ -3,   4,  -4,  -3],
        [ -3, -10,  -3,  -4],
        [  5,  -3,  -6,   3]])
array 2:
 tensor([[-1,  4,  4,  2],
        [-2, -6,  7,  9],
        [ 3, -2,  3,  3]])
array 2 sau khi chuyển vị:
 tensor([[-1, -2,  3],
        [ 4, -6, -2],
        [ 4,  7,  3],
        [ 2,  9,  3]])
Kết quả phép nhân arr_1 với  arr_2:
 tensor([[ -3, -73, -38],
        [-57,   9, -10],
        [-35,  -7,  12]])


In [9]:
tensor_1 = tf.random.uniform((3, 4), minval=-10, maxval=10, dtype=tf.dtypes.int32)
tensor_2 = tf.random.uniform((3, 4), minval=-10, maxval=10, dtype=tf.dtypes.int32)

tensor_2_transposed = tf.transpose(tensor_2)

result_matmul = tf.matmul(tensor_1, tensor_2_transposed)

print("array 1:\n", tensor_1)
print("array 2:\n", tensor_2)
print("array 2 sau khi chuyển vị:\n", tensor_2_transposed)
print("Kết quả phép nhân arr_1 với  arr_2:\n", result_matmul )

array 1:
 tf.Tensor(
[[-6 -2  0 -2]
 [ 4  4 -9  3]
 [ 7  1  2 -5]], shape=(3, 4), dtype=int32)
array 2:
 tf.Tensor(
[[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]], shape=(3, 4), dtype=int32)
array 2 sau khi chuyển vị:
 tf.Tensor(
[[-3  2  4]
 [-7 -5 -3]
 [ 9 -3 -3]
 [ 3 -5  5]], shape=(4, 3), dtype=int32)
Kết quả phép nhân arr_1 với  arr_2:
 tf.Tensor(
[[  26    8  -28]
 [-112    0   46]
 [ -25   28   -6]], shape=(3, 3), dtype=int32)


- Câu 2: Viết chương trình tạo một Numpy array, Pytorch tensor, Tensorflow tensor với các giá trị số nguyên ngẫu nhiên trong khoảng [-10, 10) với kích thước (3, 3). Sau đó hãy tính tổng của toàn bộ tensor, array, tiếp theo tính tổng theo chiều dọc, chiều ngang . Lưu ý: sử dụng seed=2024

In [11]:
arr = np.random.randint(-10, 10, (3, 3 ))

total_sum = np.sum(arr)

col_sum = np.sum(arr, axis=0)

row_sum = np.sum(arr, axis=-1)

print("Mảng:\n", arr)
print("Tổng của tất cả các phần tử trong mảng:\n", total_sum)
print("Tổng theo cột:\n", col_sum)
print("Tổng theo hàng:\n", row_sum)

Mảng:
 [[-3  8  1]
 [ 8  3 -8]
 [-1 -2 -7]]
Tổng của tất cả các phần tử trong mảng:
 -1
Tổng theo cột:
 [  4   9 -14]
Tổng theo hàng:
 [  6   3 -10]


In [12]:
tensor_1 = torch.randint(-10, 10, size=(3, 3))

tensor_sum = torch.sum(tensor_1)

tensor_sum_axis_0 = torch.sum(tensor_1, axis=0)

tensor_sum_axis_1 = torch.sum(tensor_1, axis=1)

print("tensor:\n", tensor_1)
print("Tổng các phần tử trong tensor:\n", tensor_sum)
print("Tổng theo cột:\n", tensor_sum_axis_0)
print("Tổng theo hàng:\n", tensor_sum_axis_1)

tensor:
 tensor([[-9,  3, -2],
        [-6,  7, -7],
        [ 8, -3,  0]])
Tổng các phần tử trong tensor:
 tensor(-9)
Tổng theo cột:
 tensor([-7,  7, -9])
Tổng theo hàng:
 tensor([-8, -6,  5])


In [13]:
tensor_1 = tf.random.uniform((3, 3), minval=-10, maxval=10, dtype=tf.dtypes.int32)

tensor_sum = tf.reduce_sum(tensor_1)

tensor_sum_axis_0 = tf.reduce_sum(tensor_1, axis=0)

tensor_sum_axis_1 = tf.reduce_sum(tensor_1, axis=1)

print("tensor:\n", tensor_1)
print("Tổng các phần tử trong tensor:\n", tensor_sum)
print("Tổng theo cột:\n", tensor_sum_axis_0)
print("Tổng theo hàng:\n", tensor_sum_axis_1)

tensor:
 tf.Tensor(
[[ 2  6 -6]
 [ 4 -9  3]
 [ 8  0  3]], shape=(3, 3), dtype=int32)
Tổng các phần tử trong tensor:
 tf.Tensor(11, shape=(), dtype=int32)
Tổng theo cột:
 tf.Tensor([14 -3  0], shape=(3,), dtype=int32)
Tổng theo hàng:
 tf.Tensor([ 2 -2 11], shape=(3,), dtype=int32)
