- Bài tập: Trong NLP, chúng ta cần loại bỏ 1 số từ không quan trọng (stopwords) ra khỏi câu để tránh gây nhiễu trong việc xử lý. Hãy loại bỏ các từ có trong stop_words = ["I", "love", "and", "to"] câu đầu vào "I love AI and listen to music". Hãy áp dụng List comprehension và For truyền thống để thực hiện

In [10]:
stop_words = [ "I" , "love" , "and" , "to" ]
input = " I love AI and listen to music "
output = [word for word in input.split() if word not in stop_words]
output

['AI', 'listen', 'music']

- Câu 1: Tạo mới hai Tuple: my_tuple1 = (2,3), my_tuple2 = (3,6) mỗi Tuple có 2 phần tử đại diện cho một vector trong không gian 2D.

In [11]:
my_tuple1 = (2, 3)
my_tuple2 = (3, 6)

my_tuple1, my_tuple2

((2, 3), (3, 6))

-  Câu 2: In ra kết quả của tổng và tích 2 vector trên.

In [13]:
result_vector1 = (my_tuple1[0] + my_tuple2[0], my_tuple1[1] + my_tuple2[1])
result_vector2 = (my_tuple1[0] * my_tuple2[0], my_tuple1[1] * my_tuple2[1])

result_vector1, result_vector2

((5, 9), (6, 18))

In ra kết quả của khoảng cách của hai vector trên theo công thức. Biết $distance(P, Q) = \sqrt{(p_1 − q_1)^2 + (p_2 − q_2)^2 + . . . + (p_n − q_n)^2}$

In [14]:
import math 

distance = math.sqrt((my_tuple1[0]-my_tuple2[0])**2 + (my_tuple1[1]-my_tuple2[1])**2)

distance

3.1622776601683795

- In ra vị trí của phần tử có giá trị là 3 Sử dụng cú pháp: my_tuple.index(values) để trích xuất vị trí của giá trị cần tìm.

In [16]:
my_tuple1.index(3), my_tuple2.index(3)

(1, 0)

- Câu 1: Hãy viết chương trình tạo Numpy 2 array, Pytorch tensor với từ list 1 có giá trị [1, 2, 3], list 2 có giá trị [4, 5, 6]. Sau đó sử dụng hàm hstack để nối theo trục ngang và vstack để nối theo trục dọc?

In [1]:
import numpy as np
import torch 
import tensorflow as tf

In [4]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

arr_3 = np.hstack((arr_1, arr_2))
arr_4 = np.vstack((arr_1, arr_2))

arr_1, arr_2, arr_3, arr_4

(array([1, 2, 3]),
 array([4, 5, 6]),
 array([1, 2, 3, 4, 5, 6]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [6]:
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([4, 5, 6])

tensor_3 = torch.hstack((tensor_1, tensor_2))
tensor_4 = torch.vstack((tensor_1, tensor_2))

tensor_1, tensor_2, tensor_3, tensor_4

(tensor([1, 2, 3]),
 tensor([4, 5, 6]),
 tensor([1, 2, 3, 4, 5, 6]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

- Câu 2: Hãy viết chương trình tạo Numpy 2 array, Pytorch tensor, Tensorflow tensor từ list 2D là [[1 ,2 , 3] , [4 , 5 , 6]] và [[7 , 8 , 9] , [10 , 11 ,12]]. Sau đó sử dụng hàm concanate để nối theo trục ngang và vstack để nối theo trục dọc?

In [7]:
arr_1 = np.array([[1 , 2 , 3] ,[4 , 5 , 6]])
arr_2 = np.array([[7 , 8 , 9] ,[10 , 11 , 12]])

arr_3 = np.concatenate((arr_1, arr_2), axis=0)
arr_4 = np.concatenate((arr_1, arr_2), axis=1)

arr_1, arr_2, arr_3, arr_4

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]))

In [8]:
tensor_1 = torch.tensor([[1 , 2 , 3] ,[4 , 5 , 6]])
tensor_2 = torch.tensor([[7 , 8 , 9] ,[10 , 11 , 12]])

tensor_3 = torch.cat((tensor_1, tensor_2), dim=0)
tensor_4 = torch.cat((tensor_1, tensor_2), dim=1)

tensor_1, tensor_2, tensor_3, tensor_4

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 1,  2,  3,  7,  8,  9],
         [ 4,  5,  6, 10, 11, 12]]))

In [11]:
tensor_1 = tf.constant([[1 , 2 , 3] ,[4 , 5 , 6]])
tensor_2 = tf.constant([[7 , 8 , 9] ,[10 , 11 , 12]])

tensor_3 = tf.concat((tensor_1, tensor_2), axis=0)
tensor_4 = tf.concat((tensor_1, tensor_2), axis=1)

tensor_1, tensor_2, tensor_3, tensor_4

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])>,
 <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])>)