In [1]:
import tensorflow as tf 
import torch 
import numpy as np

In [2]:
tf.random.set_seed(2024)
torch.manual_seed(2024)
np.random.seed(2024)

- Câu 1: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor trong khoảng [0, 10) với step=1?

In [3]:
arr_arange = np.arange(10)
arr_arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
tensor_arange = torch.arange(10)
tensor_arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
tensor_arange = tf.range(10)
tensor_arange

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

- Câu 2: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor là ma trận đơn vị với kích thước (3, 3).

In [7]:
arr_eye = np.eye(3)
arr_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
tensor_eye = tf.eye(3)
tensor_eye 

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [9]:
tensor_eye = torch.eye(3)
tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

- Câu 3: Hãy viết chương trình tạo Numpy array, Tensorflow tensor, Pytorch tensor ngẫu nhiên trong khoảng giá trị [0, 1] với kích thước (3, 4). Tiếp theo hãy tạo array, tensor với các giá trị là số nguyên trong khoảng [-10, 10]. 

In [11]:
arr_rand = np.random.rand(3, 4)
arr_randint = np.random.randint(-10, 10, size=(3, 4))

arr_rand, arr_randint

(array([[0.60244854, 0.96177758, 0.66436865, 0.60662962],
        [0.44915131, 0.22535416, 0.6701743 , 0.73576659],
        [0.25799564, 0.09554215, 0.96090974, 0.25176729]]),
 array([[ -6,  -2,   8,  -9],
        [  0,  -3,   6,  -2],
        [  3, -10, -10,   1]]))

In [13]:
tensor_rand = torch.rand((3, 4))
tensor_randint = torch.randint(-10, 10, size=(3, 4))

tensor_rand, tensor_randint 

(tensor([[0.5317, 0.8313, 0.9718, 0.1193],
         [0.1669, 0.3495, 0.2150, 0.6201],
         [0.4849, 0.7492, 0.1521, 0.5625]]),
 tensor([[  1,   8,   0,  -2],
         [ -9, -10,  -9,   0],
         [ -3,  -7,  -4,   8]]))

In [14]:
tensor_rand = tf.random.uniform((3, 4)) 
tensor_randint = tf.random.uniform((3,4), minval=-10, maxval=10)

tensor_rand, tensor_randint

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[0.90034294, 0.19453335, 0.36069036, 0.66361904],
        [0.76605344, 0.2159369 , 0.6261736 , 0.07380784],
        [0.22062695, 0.934368  , 0.93327904, 0.69267046]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 1.6345768 ,  5.242193  ,  0.43196487, -4.9151683 ],
        [-3.8236713 , -0.25904465, -8.645498  , -3.7031531 ],
        [ 2.0925856 ,  5.5088787 ,  7.718027  , -7.3018003 ]],
       dtype=float32)>)